# Generated by Django 5.1.2 on 2026-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_theme',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Station Commander'), ('manager', 'Sector Manager'), ('staff', 'Operations Officer'), ('customer', 'Global Citizen')], default='customer', max_length=20),
        ),
    ]
