# Generated by Django 4.2.30 on 2026-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_wishlistitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(
                blank=True, default="", help_text="External image URL"
            ),
        ),
    ]
